// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mXcy4ni4vcVtswRrbdgiRuY9scHORkM',
    appId: '1:792855206662:web:c244efa33a85fe3cb3dc87',
    messagingSenderId: '792855206662',
    projectId: 'healthportal-swe463',
    authDomain: 'healthportal-swe463.firebaseapp.com',
    storageBucket: 'healthportal-swe463.firebasestorage.app',
    measurementId: 'G-Y95K19B9X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiGcIps2_BPj_7tMeFvxyuIRw62t0jCDw',
    appId: '1:792855206662:android:5251c0d51ecc8bd1b3dc87',
    messagingSenderId: '792855206662',
    projectId: 'healthportal-swe463',
    storageBucket: 'healthportal-swe463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVx_QY1NVMFCeSwP4bjEa5-68Xj00LBYs',
    appId: '1:792855206662:ios:a51747725218ae61b3dc87',
    messagingSenderId: '792855206662',
    projectId: 'healthportal-swe463',
    storageBucket: 'healthportal-swe463.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVx_QY1NVMFCeSwP4bjEa5-68Xj00LBYs',
    appId: '1:792855206662:ios:a51747725218ae61b3dc87',
    messagingSenderId: '792855206662',
    projectId: 'healthportal-swe463',
    storageBucket: 'healthportal-swe463.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8mXcy4ni4vcVtswRrbdgiRuY9scHORkM',
    appId: '1:792855206662:web:b79ef284b165caa6b3dc87',
    messagingSenderId: '792855206662',
    projectId: 'healthportal-swe463',
    authDomain: 'healthportal-swe463.firebaseapp.com',
    storageBucket: 'healthportal-swe463.firebasestorage.app',
    measurementId: 'G-KE6XM6GMFE',
  );
}
